# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `minitest-rg` gem.
# Please instead update this file by running `bin/tapioca gem minitest-rg`.


# source://minitest-rg//lib/minitest/rg_plugin.rb#5
module Minitest
  class << self
    # source://minitest-rg//lib/minitest/rg_plugin.rb#12
    def plugin_rg_init(options); end

    # source://minitest-rg//lib/minitest/rg_plugin.rb#6
    def plugin_rg_options(opts, _options); end
  end
end

# source://minitest-rg//lib/minitest/rg_plugin.rb#20
class Minitest::RG
  # @return [RG] a new instance of RG
  #
  # source://minitest-rg//lib/minitest/rg_plugin.rb#40
  def initialize(io, colors = T.unsafe(nil)); end

  # Returns the value of attribute colors.
  #
  # source://minitest-rg//lib/minitest/rg_plugin.rb#30
  def colors; end

  # Returns the value of attribute io.
  #
  # source://minitest-rg//lib/minitest/rg_plugin.rb#30
  def io; end

  # source://minitest-rg//lib/minitest/rg_plugin.rb#63
  def method_missing(msg, *args); end

  # source://minitest-rg//lib/minitest/rg_plugin.rb#45
  def print(output); end

  # source://minitest-rg//lib/minitest/rg_plugin.rb#49
  def puts(output = T.unsafe(nil)); end

  private

  # @return [Boolean]
  #
  # source://minitest-rg//lib/minitest/rg_plugin.rb#69
  def respond_to_missing?(method_name, include_all = T.unsafe(nil)); end

  class << self
    # source://minitest-rg//lib/minitest/rg_plugin.rb#32
    def rg!(color: T.unsafe(nil)); end

    # @return [Boolean]
    #
    # source://minitest-rg//lib/minitest/rg_plugin.rb#36
    def rg?; end
  end
end

# source://minitest-rg//lib/minitest/rg_plugin.rb#23
Minitest::RG::COLORS = T.let(T.unsafe(nil), Hash)

# source://minitest-rg//lib/minitest/rg_plugin.rb#21
Minitest::RG::VERSION = T.let(T.unsafe(nil), String)
