# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `type_toolkit` gem.
# Please instead update this file by running `bin/tapioca gem type_toolkit`.


# Asserts that the receiver is not nil.
#
# You should use `not_nil!` in places where you're absolutely sure a `nil` value can't occur.
# This should be done as closely to where the value is created as possible, so that the `nil`
# value doesn't have a chance to be passed around the system. This way, failures occur close to
# the source of the problem, and are easier to fix.
#
# source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#10
module Kernel
  # source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#12
  sig { returns(T.self_type) }
  def not_nil!; end
end

# source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#17
class NilClass
  # @raise [TypeToolkit::UnexpectedNilError]
  #
  # source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#20
  sig { override.returns(T.noreturn) }
  def not_nil!; end
end

# source://type_toolkit//lib/type_toolkit/version.rb#4
module TypeToolkit; end

# An error raised when calling `#not_nil!` on a `nil` value.
#
# `UnexpectedNilError` should never occur in well-formed code, so it should never be rescued.
# This is why it inherits from `Exception` instead of `StandardError`,
# so that bare rescues clauses (like `rescue => e`) don't rescue it.
#
# source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#31
class TypeToolkit::UnexpectedNilError < ::Exception
  # @return [UnexpectedNilError] a new instance of UnexpectedNilError
  #
  # source://type_toolkit//lib/type_toolkit/ext/nil_assertions.rb#32
  def initialize(message = T.unsafe(nil)); end
end

# source://type_toolkit//lib/type_toolkit/version.rb#5
TypeToolkit::VERSION = T.let(T.unsafe(nil), String)
