# RSpec to Minitest Migration Workflow

# This workflow demonstrates how to convert RSpec test files to Minitest:
# 1. Analyzes the RSpec test to understand its purpose and dependencies
# 2. Creates a new Minitest file with equivalent assertions and test structure
# 3. Runs the tests and makes improvements until they pass

name: RSpec to Minitest Migration
model: gpt-4.1

# Target expects a glob pattern matching RSpec files to be converted
# target: "**/*_spec.rb"

tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::WriteFile
  - Roast::Tools::Grep
  - Roast::Tools::Cmd
  - Roast::Tools::CodingAgent

steps:
  - analyze_spec
  - create_minitest
  - run_and_improve
  - rubocop: $(bundle exec rubocop -A)
  - Summarize the changes made to the codebase.

# Configure the steps
analyze_spec:
  print_response: false

create_minitest:
  print_response: true

run_and_improve:
  print_response: true 

functions:
  grep:
    cache: true