# usage: roast execute examples/mcp/workflow.yml -o output.md

name: MCP Tools Example
model: gpt-4o-mini
tools:
  # SSE MCP:
  - Roast Docs:
      url: https://gitmcp.io/Shopify/roast/docs
      # Can pass headers for authentication
      # headers:
      #   - "Authorization: Bearer {{resource.api_token}}"
  # stdio MCPs are also supported
  # - GitHub:
  #     command: "docker",
  #     args:
  #       - "run"
  #       - "-i"
  #       - "--rm"
  #       - "-e"
  #       - "GITHUB_PERSONAL_ACCESS_TOKEN"
  #       - "ghcr.io/github/github-mcp-server"
  #     env:
  #       GITHUB_PERSONAL_ACCESS_TOKEN: "<YOUR_TOKEN>"
  #     only:
  #       - get_issue
  #       - get_issue_comments
  #     except:
  #       - create_issue

steps:
  - get_doc: Read the Roast docs, and tell me how to use MCP tools.
  - summarize

summarize:
  print_response: true