# typed: true
# frozen_string_literal: true

module Roast
  module Cogs
    class Agent < Cog
      # Token usage and cost information for agent execution
      #
      # Tracks the number of input and output tokens consumed during agent execution,
      # along with the associated cost in USD. This information is used to monitor
      # resource consumption and estimate execution costs.
      #
      # Usage data can represent either aggregate usage across all models or usage
      # for a specific model when tracked in the per-model breakdown.
      #
      # #### See Also
      # - `Agent::Stats` - contains aggregate and per-model usage information
      class Usage
        # The number of input tokens consumed
        #
        # Input tokens represent the text sent to the agent, including the user prompt,
        # system instructions, conversation history, and any other context provided to
        # the model. This metric is used to calculate the cost of providing input to the agent.
        #
        # #### See Also
        # - `output_tokens`
        # - `cost_usd`
        #
        #: Integer?
        attr_accessor :input_tokens

        # The number of output tokens generated
        #
        # Output tokens represent the text generated by the agent in response to the input.
        # This includes the agent's responses, reasoning, and any other text produced during
        # execution. This metric is used to calculate the cost of the agent's output.
        #
        # #### See Also
        # - `input_tokens`
        # - `cost_usd`
        #
        #: Integer?
        attr_accessor :output_tokens

        # The total cost in United States Dollars (USD)
        #
        # Represents the monetary cost of the agent execution based on the provider's pricing
        # model. This typically accounts for both input and output token usage, though pricing
        # models may vary by provider and model.
        #
        # #### See Also
        # - `input_tokens`
        # - `output_tokens`
        #
        #: Float?
        attr_accessor :cost_usd
      end
    end
  end
end
