name: dot_notation_example
description: Example demonstrating dot notation access for workflow outputs

steps:
  initialize:
    prompt: |
      Initialize the workflow with some sample data.
      
      Set output.counter to 0
      Set output.config.max_iterations to 5
      Set output.config.enabled to true

  process_items:
    repeat:
      # Using dot notation in conditions
      until: "counter >= config.max_iterations || !config.enabled?"
      steps:
        - increment_counter
        - check_status

  increment_counter:
    prompt: |
      Increment the counter by 1.
      Current counter value: {{counter}}
      
      Set output.counter to {{counter}} + 1

  check_status:
    prompt: |
      Check if we should continue processing.
      
      Current counter: {{counter}}
      Max iterations: {{config.max_iterations}}
      
      If counter is 3, set output.config.enabled to false
      Set output.status.last_checked to current counter value

  summarize:
    prompt: |
      Summarize the results:
      - Total iterations: {{counter}}
      - Last checked at: {{status.last_checked}}
      - Was enabled: {{config.enabled}}
      - Hit max iterations: {{counter >= config.max_iterations ? "Yes" : "No"}}