name: Linting with Error Recovery
tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::WriteFile
  - Roast::Tools::CodingAgent

steps:
  # Run linter on the file - may fail if there are syntax errors
  - lint_check: $(rubocop {{file}})
  
  # Analyze linter output and fix issues even if linter failed
  - analyze_lint_output
  
  # Apply fixes based on the analysis
  - apply_fixes

# Step configuration
lint_check:
  exit_on_error: false  # Continue even if rubocop exits with non-zero status