# typed: false
# frozen_string_literal: true

config do
  cmd(:echo) { print_all! }
end

execute do
  # Anonymous cog. Added to the stack directly and given an autogenerated key in cog storage
  # Use for actions you do once and forget about, don't need configuration
  cmd { "touch tmp/#{SecureRandom.uuid} " }

  # Named cog. Configuration for this specific instance will be looked up from config block
  cmd(:echo) { "echo 'Hello World!'" }
end
