# typed: true
# frozen_string_literal: true

#: self as Roast::DSL::Executor

config do
  cmd(:echo) { print_all! }
  chat(:hello) do
    self.model = :claude_opus_4 # TODO: self.model feels weird
    print_all!
  end
end

execute do
  # Anonymous cog. Added to the stack directly and given an autogenerated key in cog storage
  # Use for actions you do once and forget about, don't need configuration
  cmd { "touch tmp/#{SecureRandom.uuid} " }

  # Named cog. Configuration for this specific instance will be looked up from config block
  cmd(:echo) { "echo 'Hello World!'" }

  chat(:hello) { "say 'whats up'" }
end
