# typed: true
# frozen_string_literal: true

#: self as Roast::DSL::Executor

config do
  # TODO: make a way to do print_all on all and turn off printing on one
  cmd(:echo) { print_all! }
  cmd(:date) { print_stdout! }
  cmd(:date2) { print_all! }
  # TODO: add a way to apply config to a subset of named cog by pattern
  # cmd(/^date.*/) { print_all! }
end

execute do
  # Anonymous cog. Added to the stack directly and given an autogenerated key in cog storage
  # Use for actions you do once and forget about, don't need configuration
  cmd { |my| my.command = "touch tmp/#{SecureRandom.uuid}" }

  # Named cog. Configuration for this specific instance will be looked up from config block
  cmd(:echo) { |my| my.command = "echo 'Hello World!'" }

  # Cogs can implement input coercion for simple return values
  cmd(:date) { "date" }
  cmd(:date1) { ["date", "-h"] }
end
