inherit_from: .rubocop_todo.yml

require:
  - ./rubocop/cop/roast

plugins:
  - rubocop-sorbet

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  CacheRootDirectory: tmp
  Exclude:
    - 'bin/*'
    - 'spec/fixtures/**/*'
    - 'test/fixtures/**/*'
    - 'examples/**/*'
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  UseCache: true

Sorbet/FalseSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "test/**/*"
    - "examples/**/*"
    - "lib/roast/sorbet_runtime_stub.rb"

Roast/UseCmdRunner:
  Enabled: true
  Exclude:
    - 'lib/roast/helpers/cmd_runner.rb'
    - 'lib/roast/dsl/command_runner.rb'
    - 'roast.gemspec'

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'test/**/*.rb'
