inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  CacheRootDirectory: tmp
  Exclude:
    - 'bin/*'
    - 'spec/fixtures/**/*'
    - 'test/fixtures/**/*'
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  UseCache: true
