inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-sorbet

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  CacheRootDirectory: tmp
  Exclude:
    - 'bin/*'
    - 'spec/fixtures/**/*'
    - 'test/fixtures/**/*'
    - 'examples/**/*'
  SuggestExtensions: false
  TargetRubyVersion: 3.4
  UseCache: true

Naming/FileName:
  Exclude:
    - "lib/roast-ai.rb"

Sorbet/FalseSigil:
  Enabled: true
  Include:
    - "lib/**/*.rb"
  Exclude:
    - "test/**/*"
    - "examples/**/*"
    - "lib/roast/sorbet_runtime_stub.rb"

Style/MethodCallWithArgsParentheses:
  Enabled: true
  Exclude:
    - 'test/**/*.rb'
