name: Getting Started with Command Functions
model: default

# This example teaches you how to use command functions in Roast

tools:
  - Roast::Tools::Cmd:
      allowed_commands:
        - pwd
        - ls
        - echo

steps:
  - |
    # Welcome to Command Functions!

    I'll help you learn how to use command functions in Roast. When you configure
    the Cmd tool with allowed commands, each command becomes its own function that
    I can call.

    In this workflow, you've allowed three commands:
    - `pwd()` - Shows where we are
    - `ls(args: "...")` - Lists files and directories
    - `echo(args: "...")` - Displays messages

    Let me demonstrate each one:

    1. First, I'll use `pwd()` to show our current location
    2. Then I'll use `ls()` to see what files are here
    3. Finally, I'll use `echo()` to display a friendly message

    Let's begin!

  - basic_commands
