# typed: true
# frozen_string_literal: true

require "English"
require "active_support"
require "active_support/cache"
require "active_support/core_ext/array"
require "active_support/core_ext/hash"
require "active_support/core_ext/object/deep_dup"
require "active_support/core_ext/module/delegation"
require "active_support/core_ext/string"
require "active_support/core_ext/string/inflections"
require "active_support/isolated_execution_state"
require "active_support/notifications"
require "async"
require "async/semaphore"
require "bundler/setup"
require "json"
require "open3"
require "shellwords"
require "sqlite3"
require "optparse"
require "timeout"
require "zeitwerk"
