name: interactive_deployment
description: Interactive deployment workflow with user confirmations

steps:
  # Collect deployment information
  - input:
      prompt: "Which environment do you want to deploy to?"
      name: environment
      type: choice
      options:
        - development
        - staging
        - production
      required: true
  
  - input:
      prompt: "Enter the deployment tag/version:"
      name: deploy_tag
      required: true
      default: "latest"
  
  # Show deployment plan
  - bash:
      command: |
        echo "==================================="
        echo "       DEPLOYMENT PLAN"
        echo "==================================="
        echo "Environment: #{environment}"
        echo "Version: #{deploy_tag}"
        echo "Timestamp: $(date)"
        echo "==================================="
  
  # Confirm deployment
  - input:
      prompt: "Deploy #{deploy_tag} to #{environment}?"
      type: boolean
      default: false
      name: confirm_deploy
  
  # Execute deployment if confirmed
  - if: "#{confirm_deploy}"
    then:
      - bash:
          command: echo "🚀 Starting deployment to #{environment}..."
      
      # Simulate deployment steps
      - bash:
          command: |
            echo "🚀 Deploying version #{deploy_tag} to #{environment}"
            echo "📦 Pulling Docker image: myapp:#{deploy_tag}"
            sleep 2
            echo "🔄 Rolling out to #{environment} cluster"
            sleep 2
            echo "✅ Deployment completed successfully!"
      
      # Post-deployment verification
      - input:
          prompt: "Run smoke tests?"
          type: boolean
          default: true
          name: run_tests
      
      - if: "#{run_tests}"
        then:
          - bash:
              command: |
                echo "🧪 Running smoke tests..."
                sleep 1
                echo "✅ All tests passed!"
    else:
      - bash:
          command: echo "❌ Deployment cancelled by user."