# Apply Diff Demo
#
# This workflow demonstrates the apply_diff tool which shows users a diff
# and applies changes based on their confirmation. It's useful for making
# targeted changes to files with user approval.

name: Apply Diff Demo
model: gpt-4o-mini

tools:
  - Roast::Tools::WriteFile
  - Roast::Tools::ReadFile
  - Roast::Tools::ApplyDiff

steps:
  - create_sample_file
  - apply_simple_change

# Step configurations
create_sample_file:
  print_response: false

apply_simple_change:
  print_response: true