description: Example workflow demonstrating agent continuation and context summary features

# This example shows how to use the new coding agent parameters:
# - continue: true - continues from previous agent session
# - include_context_summary: true - includes workflow context in the prompt

target: "**/*.rb"

steps:
  # First agent step - starts fresh
  - ^analyze_codebase
  
  # Second agent step - continues from previous session
  - ^refactor_code
  
  # Third agent step - includes context summary from previous steps
  - ^add_documentation
  
  # Final verification step
  - verify_changes

# Step configurations
refactor_code:
  continue: true  # Continue from the previous agent session

add_documentation:
  include_context_summary: true  # Include workflow context in the prompt