# API Integration Workflow

# This workflow demonstrates how to create an API integration that:
# 1. Fetches data from an external source
# 2. Transforms the data into a usable format
# 3. Generates a report based on the processed data

# The workflow doesn't require a target file because it's designed to work with external APIs and data sources rather than processing specific files.

# You'll be working through a weather data processing example. This is a simulation to demonstrate the workflow pattern - no actual API calls are made.

name: API Integration Workflow
model: gpt-4o-mini

tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::Grep
  - Roast::Tools::WriteFile

# For demonstration purposes only - in production you would use a real token command
# api_token: $(echo "demo_token_123456")

steps:
  - fetch_api_data
  - transform_data
  - generate_report

# Tool configurations for API calls
fetch_api_data:
  print_response: true