name: simple_input_demo
description: Simple demonstration of input step functionality
model: gpt-4o

steps:
  # Text input
  - input:
      prompt: "What's your name?"
      name: user_name
      required: true
  
  - input:
      prompt: "Are you enjoying Roast?"
      type: boolean
      default: true
      name: enjoying_roast
  
  - input:
      prompt: "What's your favorite programming language?"
      type: choice
      options:
        - Ruby
        - Python
        - JavaScript
        - Go
        - Other
      name: favorite_language
  
  - input:
      prompt: "Create a secret password (won't be displayed):"
      type: password
      required: true
      name: secret_password
  
  - "Summarize the following inputs: {{workflow.output}}"