name: Tool Configuration Example
model: default
tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::Cmd:
      allowed_commands:
        - ls
        - pwd
        - name: echo
          description: "echo command - output text to stdout, supports > for file redirection"
        - name: cat
          description: "cat command - display file contents, concatenate files, works with pipes"
  - Roast::Tools::WriteFile

steps:
  - example_step

