# Filesystem MCP Example
# This uses the filesystem MCP server which provides safe file operations

name: Filesystem MCP Example
model: gpt-4o-mini

tools:
  # Traditional Roast tools
  - Roast::Tools::ReadFile
  
  # Filesystem MCP server
  - FileSystem:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]
      only:
        - read_file
        - list_directory
        - get_file_info

steps:
  - create_test_file
  - list_files
  - read_with_mcp

create_test_file:
  prompt: |
    First, use the read_file Roast tool to read this workflow file itself (examples/mcp/filesystem_demo/workflow.yml).
    This is just to verify traditional tools work.

list_files:
  prompt: |
    Use the FileSystem MCP tool's list_directory function to list the contents of the /tmp directory.
    The function expects a "path" parameter with value "/tmp".

read_with_mcp:
  prompt: |
    If you see any .txt or .md files in /tmp from the previous step, try reading one with the 
    FileSystem MCP tool's read_file function. Otherwise, just say "No text files found in /tmp".