name: funny_name_backstory
description: Create a humorous backstory based on your name

steps:
  # Collect user's name
  - input:
      prompt: "What's your name?"
      name: user_name
      required: true

  # Ask for preferences
  - input:
      prompt: "Pick a genre for your backstory:"
      type: choice
      options:
        - "Epic Fantasy Adventure"
        - "Cyberpunk Hacker"
        - "Time-Traveling Detective"
        - "Intergalactic Pizza Delivery"
        - "Victorian-Era Vampire Hunter"
        - "Professional Cat Whisperer"
      name: genre

  # Generate the backstory
  - create_backstory
