name: Analyze My Business
description: Examines a CSV list of orders for insights

# Default model for all steps
model: google:gemini-2.5-flash
tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::Grep

steps:
  - Read the provided CSV files.
  - "Where are most of my customers from?"
  - "What is my most popular product?"
  - Summarize the insights from the report.
