name: OpenRouter Example
api_provider: openrouter
api_token: $(echo $OPENROUTER_API_KEY)
model: google/gemini-2.0-flash-001

tools:
  - Roast::Tools::ReadFile
  - Roast::Tools::WriteFile

steps:
  - analyze_input
  - generate_response
