name: "Case/When/Else Example"

tools:
  - Roast::Tools::Cmd
  - Roast::Tools::ReadFile
  - Roast::Tools::WriteFile

target: "**/*.{rb,js,py,go}"

steps:
  - detect_language

  - case: "{{ workflow.output.detect_language }}"
    when:
      ruby:
        - analyze_ruby
        - generate_ruby_report
      javascript:
        - analyze_javascript
        - generate_js_report
      python:
        - analyze_python
        - generate_python_report
      go:
        - analyze_go
        - generate_go_report
    else:
      - analyze_generic
      - generate_generic_report

  # Another example using bash command for case expression
  - get_environment: $(echo $ENVIRONMENT || echo "development")

  - case: "{{ workflow.output.get_environment }}"
    when:
      production:
        - production_checks
        - deploy_production
      staging:
        - staging_checks
        - deploy_staging
      development:
        - run_tests
        - local_deploy
    else:
      - unknown_environment

  # Example with numeric case values
  - count_issues

  - case: "{{ workflow.output.count_issues.to_i > 10 ? 'high' : workflow.output.count_issues.to_i > 5 ? 'medium' : 'low' }}"
    when:
      high:
        - high_priority_alert
      medium:
        - medium_priority_notice
      low:
        - low_priority_info