name: JSON Data Handling Example
api_provider: openai
model: gpt-4

tools:
  - type: write_file
    allowed_paths:
      - examples/json_handling/

steps:
  - name: fetch_users
    prompt: |
      Generate a JSON array of 3 user objects. Each user should have:
      - id (number)
      - name (string)
      - email (string)
      - active (boolean)
    json: true

  - name: fetch_metadata
    prompt: |
      Generate a JSON object with metadata about a dataset:
      - total_records (number)
      - last_updated (ISO date string)
      - categories (array of strings)
      - filters (object with status and sort fields)
    json: true

  - name: process_data
    prompt: |
      Based on the users data: {{output.fetch_users}}
      And metadata: {{output.fetch_metadata}}
      
      Create a summary report describing:
      1. How many active users there are
      2. The categories available
      3. When the data was last updated

  - name: save_report
    tool: write_file
    path: examples/json_handling/report.txt
    content: |
      # JSON Data Processing Report
      
      ## Users Data
      {{output.fetch_users}}
      
      ## Metadata
      {{output.fetch_metadata}}
      
      ## Summary
      {{output.process_data}}