name: Test Grading

tools:
  - Roast::Tools::Grep
  - Roast::Tools::ReadFile
  - Roast::Tools::SearchFile

steps:
  - read_dependencies
  -
    - verify_test_helpers
    - verify_mocks_and_stubs
  - generate_grades
  - calculate_final_grade
  - format_result
  - generate_recommendations

analyze_coverage:
  json: true

generate_grades:
  model: o3
  json: true

generate_recommendations:
  model: o3
  json: true

