description: Example workflow demonstrating agent steps

# Agent steps send prompts directly to CodingAgent (e.g., Claude Code)
# without the intermediate LLM translation layer

target: "**/*.rb"

steps:
  # Regular step - goes through LLM first for analysis and judgment
  - identify_code_smells
  
  # Agent step - direct to CodingAgent for precise refactoring
  - ^apply_refactorings
  
  # Regular step - verify changes and provide summary
  - summarize_improvements