# Workflow Generator
#
# This workflow generates new Roast workflows based on user descriptions.
# It gets user input, analyzes the request, generates an appropriate workflow structure,
# and creates all necessary files in a new directory.

name: Workflow Generator
model: gpt-4o-mini

tools:
  - Roast::Tools::WriteFile
  - Roast::Tools::ReadFile
  - Roast::Tools::Cmd
  - Roast::Tools::AskUser

steps:
  - get_user_input
  - info_from_roast
  - analyze_user_request
  - create_workflow_files

# Step configurations
get_user_input:
  print_response: false
  json: true
  auto_loop: false

analyze_user_request:
  print_response: true

generate_workflow_structure:
  print_response: true

create_workflow_files:
  print_response: false