name: analyze_codebase
description: Analyze a single codebase with pre/post processing support
model: gpt-4o
target: "src/main.rb"

# Pre-processing: Gather context before analyzing the main file
pre_processing:
  - gather_dependencies
  - setup_analysis_tools

# Main workflow: Analyze the target file
steps:
  - analyze_code_quality
  - identify_improvements
  - generate_recommendations

# Post-processing: Generate final report
post_processing:
  - summarize_findings
  - create_action_items