# Environment Variable Interpolation Demo
# This shows how ENV variables are interpolated in MCP tool configurations

name: ENV Interpolation Demo
model: o4-mini

tools:
  - Roast::Tools::ReadFile
  
  # Filesystem MCP with interpolated path
  # The user's home directory will be resolved from ENV['HOME']
  - UserFiles:
      command: npx
      args: ["-y", "@modelcontextprotocol/server-filesystem", "{{ENV['HOME'] || '/tmp'}}"]
      only:
        - list_directory
        - get_file_info

steps:
  - show_env: |
      First, tell me what user is running this workflow. The current user is: {{ENV['USER'] || 'unknown'}}
      And their home directory is: {{ENV['HOME'] || 'not set'}}
      
  - list_home: |
      Now use the UserFiles MCP tool's list_directory function to list the user's home directory.
      Just show the first 5-10 items you find.


show_env:
  print_response: true

list_home:
  model: gpt-4o-mini
  print_response: true