name: test_optimization
model: gpt-4o
target: "test/**/*_test.rb"

# Pre-processing steps run once before any test files are processed
pre_processing:
  - gather_baseline_metrics
  - setup_test_environment

# Main workflow steps run for each test file
steps:
  - analyze_test_file
  - improve_test_coverage
  - optimize_test_performance
  - validate_changes

# Post-processing steps run once after all test files have been processed
post_processing:
  - aggregate_metrics
  - generate_summary_report
  - cleanup_environment