name: Direct Coerce Syntax Demo
description: Demonstrates the simplified coerce_to syntax without config blocks

steps:
  # Example 1: Direct coerce_to on repeat
  - repeat:
      until: "check_api_ready"
      coerce_to: boolean  # Direct syntax - no config block needed
      max_iterations: 5
      steps:
        - check_api_ready:
            prompt: "Check if the API endpoint returns a 200 status"
        - wait: 2
  
  # Example 2: Direct coerce_to on each  
  - get_data_sources:
      prompt: "List available data sources, one per line"
  
  - each: "get_data_sources"
    as: "source"
    coerce_to: iterable  # Direct syntax
    steps:
      - validate_source: "Validating {{source}}..."
      - process_source:
          prompt: "Process data from {{source}}"
  
  # Example 3: Multiple configuration options
  - repeat:
      until: "all_tests_pass"
      coerce_to: llm_boolean  # Override default
      print_response: true     # Other options work too
      max_iterations: 10
      steps:
        - run_tests: "$(rake test)"
        - all_tests_pass:
            prompt: "Did all tests pass successfully?"